export const ADD_INGREDIENT = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENTS"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILED = "FETCHED_INGREDIENTS_FAILED"

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PUCRCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'